const express = require('express');
const path = require('path');
const fs = require('fs');
const bodyParser = require('body-parser');
const cors = require('cors');
const nodemailer = require('nodemailer');
require('dotenv').config();

const app = express();
const PORT = process.env.PORT || 5500;
const DATA_DIR = path.join(__dirname, 'data');
const REQUESTS_FILE = path.join(DATA_DIR, 'requests.json');

app.use(cors());
app.use(bodyParser.urlencoded({ extended: true }));
app.use(bodyParser.json());
app.use(express.static(path.join(__dirname, 'public')));

// Ensure data directory and file exist
if (!fs.existsSync(DATA_DIR)) fs.mkdirSync(DATA_DIR);
if (!fs.existsSync(REQUESTS_FILE)) fs.writeFileSync(REQUESTS_FILE, '[]', 'utf8');

// Nodemailer transporter using Gmail SMTP (App Password recommended)
const EMAIL_ADMIN = process.env.EMAIL_ADMIN;
const EMAIL_PASS = process.env.EMAIL_PASS;
const EMAIL_TO = process.env.EMAIL_TO || EMAIL_ADMIN;
const EMAIL_FROM_NAME = process.env.EMAIL_FROM_NAME || 'CareVo Health Hub';


// GMAIL TRANSPORTER
const transporter = nodemailer.createTransport({
  service: "gmail",
  auth:{
    user:EMAIL_ADMIN,
    pass:EMAIL_PASS
  }
})

// Basic escaping helper
function escapeHtml(str) {
  if (!str) return '';
  return String(str)
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#39;');
}

// Convert a booking entry to HTML for admin email
function bookingToHtml(entry) {
  const p = entry.payload || {};
  const tests = (p.tests && p.tests.length) ? p.tests.map(t => `<li>${escapeHtml(t)}</li>`).join('') : '<li>None selected</li>';
  return `
    <div style="font-family:system-ui,Segoe UI,Roboto,Helvetica,Arial; color:#0b2545;">
      <h2>Booking #${entry.id}</h2>
      <p><strong>Time:</strong> ${escapeHtml(entry.timestamp || '')}</p>
      <ul>
        <li><strong>Full Name:</strong> ${escapeHtml(p.fullName || '')}</li>
        <li><strong>Phone:</strong> ${escapeHtml(p.phone || '')}</li>
        <li><strong>Email:</strong> ${escapeHtml(p.email || '')}</li>
        <li><strong>Age:</strong> ${escapeHtml(p.age || '')}</li>
        <li><strong>Sex:</strong> ${escapeHtml(p.sex || '')}</li>
        <li><strong>Institution:</strong> ${escapeHtml(p.institution || '')}</li>
        <li><strong>Preferred Date:</strong> ${escapeHtml(p.date || '')}</li>
        <li><strong>Preferred Time:</strong> ${escapeHtml(p.timeSlot || '')}</li>
      </ul>
      <h4>Selected Tests</h4>
      <ul>${tests}</ul>
      <h4>Health Info</h4>
      <ul>
        <li><strong>Symptoms:</strong> ${escapeHtml(p.symptoms || '')}</li>
        <li><strong>Conditions:</strong> ${escapeHtml(p.conditions || '')}</li>
        <li><strong>Medications:</strong> ${escapeHtml(p.meds || '')}</li>
        <li><strong>Consent Given:</strong> ${p.consent ? 'Yes' : 'No'}</li>
      </ul>
      <hr>
      <p style="font-size:0.9rem;color:#6b7280">This message was generated by CareVo Health Hub.</p>
    </div>
  `;
}

// Create confirmation email for user (if email present)
function userConfirmationHtml(entry) {
  const p = entry.payload || {};
  const tests = (p.tests && p.tests.length) ? `<ul>${p.tests.map(t => `<li>${escapeHtml(t)}</li>`).join('')}</ul>` : '<p>No tests selected.</p>';
  return `
    <div style="font-family:system-ui,Segoe UI,Roboto,Helvetica,Arial; color:#0b2545;">
      <h2>CareVo Screening Request Received</h2>
      <p>Hi ${escapeHtml(p.fullName || 'Student')},</p>
      <p>Thank you for requesting a screening with CareVo Health Hub. We have received your request and will contact you via WhatsApp within 24 hours to confirm the appointment details.</p>
      <h4>Your details</h4>
      <ul>
        <li><strong>Phone:</strong> ${escapeHtml(p.phone || '')}</li>
        <li><strong>Institution:</strong> ${escapeHtml(p.institution || '')}</li>
        <li><strong>Preferred Date:</strong> ${escapeHtml(p.date || '')}</li>
        <li><strong>Preferred Time:</strong> ${escapeHtml(p.timeSlot || '')}</li>
      </ul>
      <h4>Requested tests</h4>
      ${tests}
      <p>If you need to change anything, reply to this email or contact us on WhatsApp.</p>
      <p style="font-size:0.95rem; color:#6b7280">CareVo Health Hub — Student-focused screening coordinated with licensed partner laboratories.</p>
    </div>
  `;
}

// send single booking email to admin
async function sendBookingEmailToAdmin(entry) {
  if (!transporter) return { ok: false, reason: 'transporter-not-configured' };
  const subject = `CareVo Booking Request — ${entry.payload?.fullName || 'New Request'}`;
  const userEmail = entry.payload?.email;
  const mail = {
    from: `"${EMAIL_FROM_NAME}" <${EMAIL_ADMIN}>`,
    replyTo: userEmail,
    to: EMAIL_ADMIN,
    subject,
    html: bookingToHtml(entry)
  };
  const info = await transporter.sendMail(mail);
  return { ok: true, info };
}

// send confirmation email to user
async function sendConfirmationEmailToUser(entry) {
  if (!transporter) return { ok: false, reason: 'transporter-not-configured' };
  const userEmail = entry.payload?.email;
  if (!userEmail) return { ok: false, reason: 'no-user-email' };
  const subject = 'CareVo Screening Request Received';
  const mail = {
    from: `"${EMAIL_FROM_NAME}" <${EMAIL_ADMIN}>`,
    to: userEmail,
    subject,
    html: userConfirmationHtml(entry)
  };
  const info = await transporter.sendMail(mail);
  return { ok: true, info };
}

// API: create booking
app.post('/api/bookings', async (req, res) => {
  try {
    const payload = req.body || {};
    const timestamp = new Date().toISOString();
    const entry = { id: Date.now(), timestamp, payload };
    const current = JSON.parse(fs.readFileSync(REQUESTS_FILE, 'utf8'));
    current.push(entry);
    // fs.writeFileSync(REQUESTS_FILE, JSON.stringify(current, null, 2), 'utf8');

    // Attempt to send admin and user emails concurrently; do not block booking save on failures.
    if (transporter) {
      const adminPromise = sendBookingEmailToAdmin(entry).catch(err => ({ ok: false, err }));
      const userPromise = sendConfirmationEmailToUser(entry).catch(err => ({ ok: false, err }));
      const [adminResult, userResult] = await Promise.allSettled([adminPromise, userPromise]);

      // Log results
      if (adminResult.status === 'fulfilled' && adminResult.value.ok) {
        console.log(`Admin email sent for booking ${entry.id}`);
      } else {
        console.warn('Admin email error:', adminResult.status === 'rejected' ? adminResult.reason : adminResult.value);
      }

      if (userResult.status === 'fulfilled' && userResult.value.ok) {
        console.log(`User confirmation email sent to ${entry.payload.email} for booking ${entry.id}`);
      } else {
        // userResult may be ok:false with reason 'no-user-email' or an error
        console.warn('User email result:', userResult.status === 'rejected' ? userResult.reason : userResult.value);
      }
    } else {
      console.warn('Transporter not configured; skipped email sending.');
    }

    res.json({
      success: true,
      message: 'Thank you. Your screening request has been received. You will be contacted via WhatsApp within 24 hours to confirm your appointment.',
      data: entry
    });
  } catch (err) {
    console.error(err);
    res.status(500).json({ success: false, message: 'Server error saving request.' });
  }
});

// API: list bookings
app.get('/api/book', (req, res) => {
  try {
    const current = JSON.parse(fs.readFileSync(REQUESTS_FILE, 'utf8'));
    res.json({ success: true, bookings: current });
  } catch (err) {
    console.error(err);
    res.status(500).json({ success: false, message: 'Unable to read bookings.' });
  }
});

// API: send all bookings to configured EMAIL_TO (admin)
// If ADMIN_SECRET set, require 'x-admin-secret' header or adminSecret body value
app.post('/api/booking', async (req, res) => {
  try {
    if (!transporter) {
      return res.status(500).json({ success: false, message: 'Email sending is not configured on the server.' });
    }
    const ADMIN_SECRET = process.env.ADMIN_SECRET;
    if (ADMIN_SECRET) {
      const provided = req.headers['x-admin-secret'] || req.body?.adminSecret;
      if (!provided || provided !== ADMIN_SECRET) {
        return res.status(401).json({ success: false, message: 'Unauthorized. Missing or invalid admin secret.' });
      }
    }
    const current = JSON.parse(fs.readFileSync(REQUESTS_FILE, 'utf8'));
    // Compose HTML for all bookings
    const htmlParts = current.map(b => bookingToHtml(b)).join('');
    const subject = `CareVo Bookings — Full List (${current.length} entries)`;
    const mail = {
      from: `"${EMAIL_FROM_NAME}" <${EMAIL_ADMIN}>`,
      to: EMAIL_TO,
      subject,
      html: `<div style="font-family:system-ui,Segoe UI,Roboto,Helvetica,Arial; color:#0b2545;">
               <h1>CareVo Bookings (${current.length})</h1>
               ${htmlParts}
             </div>`
    };
    await transporter.sendMail(mail);
    return res.json({ success: true, message: `Sent ${current.length} bookings to ${EMAIL_TO}` });
  } catch (err) {
    console.error(err);
    res.status(500).json({ success: false, message: 'Server error sending bookings.' });
  }
});

// Fallback: serve index.html for non-API GET requests.
app.use((req, res, next) => {
  if (req.method === 'GET' && !req.path.startsWith('/api/')) {
    res.sendFile(path.join(__dirname, 'public', 'index.html'));
  } else {
    next();
  }
});

app.use((req, res) => {
  res.status(404).send('Not found');
});

app.listen(PORT, () => {
  console.log(`CareVo site running at http://localhost:${PORT}`);
});